/*
RaspiDevKit v1.0.0
This code is autogenerated by raspidevkit
The following libraries may be required to compile to code:

*/

int currentCommand = -1;

void setup() {
  Serial.begin(9600);
  pinMode(1, OUTPUT);
  pinMode(4, OUTPUT);
}

void loop() {
  if (currentCommand == -1) {
    recieveCommand();
  }

  else if (currentCommand == 0) {
    turnOnArduinoLed0();
  }

  else if (currentCommand == 1) {
    turnOffArduinoLed0();
  }

  else if (currentCommand == 2) {
    turnOnArduinoLed1();
  }

  else if (currentCommand == 3) {
    turnOffArduinoLed1();
  }
}

/*
 * Recieve command from Raspberry Pi
 */
void recieveCommand() {
  if (Serial.available()) {
    int sent = Serial.readStringUntil("\r\n").toInt();
    Serial.print("ok\r\n");
    currentCommand = sent;
  }
}

/*
 * Send response to Raspberry Pi
 */
void sendResponse(String response) {
  Serial.print(response + "\r\n");
}

void turnOnArduinoLed0() {
  digitalWrite(1, HIGH);
}
void turnOffArduinoLed0() {
  digitalWrite(1, LOW);
}
void turnOnArduinoLed1() {
  digitalWrite(4, HIGH);
}
void turnOffArduinoLed1() {
  digitalWrite(4, LOW);
}
