/*
RaspiDevKit v1.0.0
This code is autogenerated by raspidevkit
The following libraries may be required to compile to code:

*/

$header

int currentCommand = -1;

void setup(){
    Serial.begin($baudrate);
    $setup
}

void loop(){
    if(currentCommand == -1){
        recieveCommand();
    } 
    
    $loop
}

/*
 * Recieve command from Raspberry Pi 
*/
void recieveCommand(){
    if(Serial.available()){
        int sent = Serial.readStringUntil("$terminator").toInt();
        Serial.print("ok$terminator");
        currentCommand = sent;
    }
}

/*
 * Send response to Raspberry Pi 
*/
void sendResponse(String response){
    Serial.print(response + "$terminator");
}

$methods